t = (input('Digite algo:'))
print (f'O tipo primitivo desse item é {type(t)}')
print (f'Só tem espaços? {t.isspace()}')
print (f'É um número?{t.isnumeric()}')
print (f'É alfabético?{t.isalpha()}')
print (f'É alfanúmerico? {t.isalnum()}')
print (f'Está em maiúsculas?{t.isupper()}')
print (f'Está em minúsculas?{t.islower()}')
print (f'Está capitalizada?{t.isascii()}')
print (t.isdigit(), t.isprintable())
