nome = input('Qual é o seu nome?')
print('Olá', nome, '! Prazer em te conhecer')
dia = input('Que dia você nasceu?')
mes = input('Que mês você nasceu?')
ano = input('Que ano você nasceu?')
print('Você nasceu no dia', dia, 'de', mes, 'de', ano, '. Correto?')
femea = input('Quantas gatas femêas você tem?')
macho = input('Quantos gatos machos você tem?')
soma = int(femea) + int(macho)
print('Você tem', soma, 'gatos. Correto?')